### PR TITLE
SNI & ECC Support

### LINKED ISSUE #2: SNI Support
Given the large number of sites that require SNI (~30% of the Alexa top 1 million), ideally SNI support should be added to this.

I've not had time to write up a patch to add it; if I get a chance, I will, unless someone else gets to it first.

### PR DESCRIPTION
**Pull request by adamcaudill**
This change adds support for SNI, and ECC-based cipher suites.

Fixes #2

### CODE REVIEW

**Comment by supergicko** [comment]
@arlimus do you plan / have time to have look on this if possible? would be really cool to have SNI support for sslshake, and then the ssl ressource in inspec :)

cheers

**Comment by arlimus** [comment]
So sorry this took so long! I was offline during the last few weeks (moving is hard).
Thank you for you contribution!!

**Comment by adamcaudill** [comment]
Thanks @arlimus! No problem, I know the pain of moving quite well. 

Thank you for the project - once this change is released, I'll be using it in https://github.com/adamcaudill/yawast, which will improve its scanning ability, and help identify configuration issues without the issues of dealing with OpenSSL. This is a real win for making systems more secure.

**Comment by arlimus** [comment]
Wow nice, thank you for sharing!!

**Comment by supergicko** [comment]
@arlimus thank you very much!

**Comment by arlimus** [comment]
@supergicko @alexpop @adamcaudill just released as 1.1.0

I'm actually looking for a few more extension to the lib 😁
also need to get a bit of maintenance done for this project, will do this week

**Comment by supergicko** [comment]
@arlimus thx.

inspec will get it in the next release, am i right?

let me know when you need support

**Comment by arlimus** [comment]
@supergicko Yes it will 👍 @alexpop asked me about it this morning too, we will make sure it is included this week

**Comment by supergicko** [comment]
nice !! thx all!

**Pull request merged**
